
-- ====================================================================
-- PRODUCTION MIGRATION & SETUP SCRIPT (NON-DESTRUCTIVE)
-- ====================================================================

-- 1. Create Tables (Only if they don't exist)
CREATE TABLE IF NOT EXISTS team_members (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    username TEXT UNIQUE,
    "password" TEXT,
    title TEXT,
    role TEXT,
    "avatarUrl" TEXT,
    "activityScore" INTEGER DEFAULT 0,
    "linkedStudentSlug" TEXT
);

CREATE TABLE IF NOT EXISTS students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    department TEXT,
    intake TEXT,
    bio TEXT,
    "avatarUrl" TEXT,
    "galleryImages" TEXT[] DEFAULT '{}',
    achievements JSONB DEFAULT '[]',
    courses JSONB DEFAULT '[]',
    cgpa JSONB DEFAULT '[]',
    "socialLinks" JSONB DEFAULT '[]',
    "contactEmail" TEXT,
    views INTEGER DEFAULT 0,
    "isFeatured" BOOLEAN DEFAULT false,
    "isLocked" BOOLEAN DEFAULT true, 
    status TEXT DEFAULT 'active',
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS campus_memories (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    year INTEGER NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    images TEXT[] DEFAULT '{}',
    date DATE NOT NULL,
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    type TEXT,
    "studentName" TEXT,
    department TEXT,
    content JSONB,
    "submittedAt" TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'pending'
);

CREATE TABLE IF NOT EXISTS notices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT,
    content TEXT,
    type TEXT,
    "isPinned" BOOLEAN DEFAULT false,
    "isArchived" BOOLEAN DEFAULT false,
    "postedAt" TIMESTAMPTZ DEFAULT now(),
    "expiresAt" TIMESTAMPTZ,
    "attachmentUrl" TEXT
);

CREATE TABLE IF NOT EXISTS resources (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT,
    type TEXT,
    department TEXT,
    intake TEXT,
    subject TEXT,
    "authorName" TEXT,
    "downloadUrl" TEXT,
    "uploadDate" TIMESTAMPTZ DEFAULT now(),
    downloads INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1
);

CREATE TABLE IF NOT EXISTS campus_images (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    url TEXT,
    "uploadedAt" TIMESTAMPTZ DEFAULT now()
);

CREATE TABLE IF NOT EXISTS site_config (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "logoUrl" TEXT,
    contact JSONB
);

CREATE TABLE IF NOT EXISTS audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    action TEXT,
    actor TEXT,
    target TEXT,
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- 2. Add Missing Columns (If tables were created in older versions)
ALTER TABLE students ADD COLUMN IF NOT EXISTS cgpa JSONB DEFAULT '[]';
ALTER TABLE students ADD COLUMN IF NOT EXISTS courses JSONB DEFAULT '[]';
ALTER TABLE students ADD COLUMN IF NOT EXISTS "isLocked" BOOLEAN DEFAULT true;
ALTER TABLE team_members ADD COLUMN IF NOT EXISTS "password" TEXT;
ALTER TABLE team_members ADD COLUMN IF NOT EXISTS "linkedStudentSlug" TEXT;

-- 3. Security Policies (Idempotent)
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE campus_memories ENABLE ROW LEVEL SECURITY;

-- Resetting policies to ensure they are always correct
DROP POLICY IF EXISTS "Public read team" ON team_members;
CREATE POLICY "Public read team" ON team_members FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read students" ON students;
CREATE POLICY "Public read students" ON students FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read notices" ON notices;
CREATE POLICY "Public read notices" ON notices FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read resources" ON resources;
CREATE POLICY "Public read resources" ON resources FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public read memories" ON campus_memories;
CREATE POLICY "Public read memories" ON campus_memories FOR SELECT USING (true);

DROP POLICY IF EXISTS "Public insert submissions" ON submissions;
CREATE POLICY "Public insert submissions" ON submissions FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Admin all" ON students;
CREATE POLICY "Admin all" ON students FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin all team" ON team_members;
CREATE POLICY "Admin all team" ON team_members FOR ALL USING (true);

DROP POLICY IF EXISTS "Admin all memories" ON campus_memories;
CREATE POLICY "Admin all memories" ON campus_memories FOR ALL USING (true);

-- 4. Initial Seed Data (Only if not already present)
INSERT INTO site_config (id, contact) 
VALUES (1, '{"address": "BIMT Campus, Dhaka, Bangladesh", "email": "contact@bimt.edu.bd", "phone": "+880 1712 345 678"}')
ON CONFLICT (id) DO NOTHING;

INSERT INTO team_members ("fullName", username, "password", title, role, "avatarUrl", "activityScore") 
VALUES ('Ahamed Alex', 'alex', 'admin123', 'Head of Operations', 'super_admin', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop', 1500)
ON CONFLICT (username) DO NOTHING;
