
-- ====================================================================
-- SUPABASE SETUP SCRIPT (WITH DEMO DATA)
-- Run this entire script in the SQL Editor of your Supabase Dashboard
-- ====================================================================

-- QUICK FIXES:
-- ALTER TABLE students ADD COLUMN "isLocked" BOOLEAN DEFAULT true;
-- ALTER TABLE team_members ADD COLUMN "password" TEXT;

-- 1. DROP EXISTING TABLES (Clean Slate for Demo)
DROP TABLE IF EXISTS audit_logs;
DROP TABLE IF EXISTS site_config;
DROP TABLE IF EXISTS campus_images;
DROP TABLE IF EXISTS resources;
DROP TABLE IF EXISTS notices;
DROP TABLE IF EXISTS submissions;
DROP TABLE IF EXISTS students;
DROP TABLE IF EXISTS team_members;

-- 2. CREATE TABLES

-- Team Members (New Table for Admin Display & Auth)
CREATE TABLE team_members (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    username TEXT UNIQUE, -- Username should be unique
    "password" TEXT,      -- Storing plain text for this specific demo requirement (Use Auth or Hash in Prod)
    title TEXT,
    role TEXT, -- 'super_admin' or 'moderator'
    "avatarUrl" TEXT,
    "activityScore" INTEGER DEFAULT 0,
    "linkedStudentSlug" TEXT
);

-- Students Table
CREATE TABLE students (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    "fullName" TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    department TEXT,
    intake TEXT,
    bio TEXT,
    "avatarUrl" TEXT,
    "galleryImages" TEXT[] DEFAULT '{}',
    achievements JSONB DEFAULT '[]',
    "socialLinks" JSONB DEFAULT '[]',
    "contactEmail" TEXT,
    views INTEGER DEFAULT 0,
    "isFeatured" BOOLEAN DEFAULT false,
    "isLocked" BOOLEAN DEFAULT true, 
    status TEXT DEFAULT 'active',
    "createdAt" TIMESTAMPTZ DEFAULT now()
);

-- Submissions Table
CREATE TABLE submissions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    type TEXT,
    "studentName" TEXT,
    department TEXT,
    content JSONB,
    "submittedAt" TIMESTAMPTZ DEFAULT now(),
    status TEXT DEFAULT 'pending'
);

-- Notices Table
CREATE TABLE notices (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT,
    content TEXT,
    type TEXT,
    "isPinned" BOOLEAN DEFAULT false,
    "isArchived" BOOLEAN DEFAULT false,
    "postedAt" TIMESTAMPTZ DEFAULT now(),
    "expiresAt" TIMESTAMPTZ,
    "attachmentUrl" TEXT
);

-- Resources Table
CREATE TABLE resources (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    title TEXT,
    type TEXT,
    department TEXT,
    intake TEXT,
    subject TEXT,
    "authorName" TEXT,
    "downloadUrl" TEXT,
    "uploadDate" TIMESTAMPTZ DEFAULT now(),
    downloads INTEGER DEFAULT 0,
    version INTEGER DEFAULT 1
);

-- Campus Images Table
CREATE TABLE campus_images (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    url TEXT,
    "uploadedAt" TIMESTAMPTZ DEFAULT now()
);

-- Site Config Table
CREATE TABLE site_config (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "logoUrl" TEXT,
    contact JSONB
);

-- Audit Logs Table
CREATE TABLE audit_logs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    action TEXT,
    actor TEXT,
    target TEXT,
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT now()
);

-- 3. STORAGE SETUP
INSERT INTO storage.buckets (id, name, public) 
VALUES ('public', 'public', true)
ON CONFLICT (id) DO NOTHING;

-- 4. ENABLE RLS
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE notices ENABLE ROW LEVEL SECURITY;
ALTER TABLE resources ENABLE ROW LEVEL SECURITY;
ALTER TABLE submissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE campus_images ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE team_members ENABLE ROW LEVEL SECURITY;

-- 5. RLS POLICIES

-- Public Read Policies
-- Important: For team_members, we allow read so login checks can happen (client-side filter applied for sensitive data)
CREATE POLICY "Public read team" ON team_members FOR SELECT USING (true);
CREATE POLICY "Public read students" ON students FOR SELECT USING (true);
CREATE POLICY "Public read notices" ON notices FOR SELECT USING (true);
CREATE POLICY "Public read resources" ON resources FOR SELECT USING (true);
CREATE POLICY "Public read images" ON campus_images FOR SELECT USING (true);
CREATE POLICY "Public read config" ON site_config FOR SELECT USING (true);

-- Public Write (Submissions)
CREATE POLICY "Public insert submissions" ON submissions FOR INSERT WITH CHECK (true);

-- Admin Full Access (Simplified for Demo using Anon Key)
CREATE POLICY "Admin all team" ON team_members FOR ALL USING (true);
CREATE POLICY "Admin all students" ON students FOR ALL USING (true);
CREATE POLICY "Admin all notices" ON notices FOR ALL USING (true);
CREATE POLICY "Admin all resources" ON resources FOR ALL USING (true);
CREATE POLICY "Admin all images" ON campus_images FOR ALL USING (true);
CREATE POLICY "Admin all config" ON site_config FOR ALL USING (true);
CREATE POLICY "Admin all logs" ON audit_logs FOR ALL USING (true);
CREATE POLICY "Admin all submissions" ON submissions FOR ALL USING (true);

-- Storage Policies
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'public' );
DROP POLICY IF EXISTS "Public Upload" ON storage.objects;
CREATE POLICY "Public Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'public' );

-- 6. INSERT DEMO DATA

-- Config
INSERT INTO site_config (id, contact) 
VALUES (1, '{"address": "BIMT Campus, Dhaka, Bangladesh", "email": "contact@bimt.edu.bd", "phone": "+880 1712 345 678"}');

-- Team Members (Initial Admins)
-- Passwords are plaintext for this custom auth demo. In real apps, use Supabase Auth.
INSERT INTO team_members ("fullName", username, "password", title, role, "avatarUrl", "activityScore") VALUES
('Ahamed Alex', 'alex', 'admin123', 'Head of Operations', 'super_admin', 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400&h=400&fit=crop', 1500),
('Fatima Begum', 'fatima', 'mod123', 'Student Welfare Lead', 'moderator', 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop', 850),
('Rahim Chowdhury', 'rahim', 'mod123', 'Event Coordinator', 'moderator', 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=400&h=400&fit=crop', 620),
('Nadia Islam', 'nadia', 'mod123', 'Academic Affairs', 'moderator', 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop', 450),
('Tanvir Ahmed', 'tanvir', 'mod123', 'Tech Support', 'moderator', 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&h=400&fit=crop', 300);

-- Students (Bengali Names)
INSERT INTO students ("fullName", slug, department, intake, bio, "avatarUrl", status, "isFeatured", "isLocked", achievements, "socialLinks") VALUES
('Arafat Rahman', 'arafat-rahman', 'Computer Science', 'Fall 2023', 'Aspiring Full Stack Developer. Love building tools that solve real-world problems. Organizer of the BIMT CodeFest.', 'https://images.unsplash.com/photo-1633332755192-727a05c4013d?w=400&h=400&fit=crop', 'active', true, true, '[{"title": "Hackathon Winner", "date": "2023-11-20", "description": "1st place in Inter-Uni Hackathon"}]', '[{"platform": "github", "url": "https://github.com"}]'),

('Sumaiya Akter', 'sumaiya-akter', 'Business Administration', 'Spring 2024', 'Focused on Digital Marketing and Entrepreneurship. Currently working on a startup idea for campus food delivery.', 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=400&h=400&fit=crop', 'active', true, true, '[]', '[{"platform": "linkedin", "url": "https://linkedin.com"}]'),

('Sahil Hasan', 'sahil-hasan', 'Engineering', 'Fall 2022', 'Robotics enthusiast. Lead member of the BIMT Robotics Club. Working on an autonomous drone project.', 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop', 'active', false, true, '[{"title": "Robotics Fair Runner-up", "date": "2023-08-10", "description": "National Science Fair"}]', '[]'),

('Nusrat Jahan', 'nusrat-jahan', 'Arts & Humanities', 'Spring 2023', 'Passionate about Bengali Literature and History. Editor of the "BIMT Voice" campus magazine.', 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400&h=400&fit=crop', 'active', true, true, '[{"title": "Best Writer Award", "date": "2023-05-15", "description": "Annual literature fest"}]', '[]'),

('Jamal Uddin', 'jamal-uddin', 'Medical Sciences', 'Fall 2021', 'Public health researcher. Conducted a campus-wide survey on mental health awareness.', 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=400&h=400&fit=crop', 'graduated', false, true, '[]', '[]');

-- Notices
INSERT INTO notices (title, content, type, "isPinned", "postedAt") VALUES
('Final Exam Schedule - Spring 2024', 'The final examination schedule has been published. Please check the notice board near the admin office or download the PDF attached.', 'exam', true, now()),
('Pohela Boishakh Celebration', 'Join us for the Mongol Shobhajatra and cultural program at the main field this Sunday. Wear traditional attire!', 'event', true, now() - interval '1 day'),
('Library Maintenance', 'The central library will be closed this Friday for server maintenance. Online resources will remain accessible.', 'campus', false, now() - interval '3 days'),
('Debate Club Registration', 'New member recruitment for the Debate Club is open until the 25th. Visit the club room to sign up.', 'campus', false, now() - interval '5 days'),
('Guest Lecture on AI', 'Dr. K. Ahmed will be delivering a lecture on "The Future of AI in Bangladesh" at the Auditorium.', 'course', false, now() - interval '1 week');

-- Resources
INSERT INTO resources (title, type, department, subject, "authorName", "downloadUrl", "uploadDate", downloads) VALUES
('Data Structures & Algo Notes', 'note', 'Computer Science', 'CS-101', 'Arafat Rahman', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', now(), 120),
('Marketing 101 Slides', 'note', 'Business Administration', 'MKT-200', 'Sumaiya Akter', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', now() - interval '2 days', 45),
('Robotics Club Constitution', 'paper', 'Engineering', 'General', 'Sahil Hasan', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', now() - interval '5 days', 12),
('Modern Bengali Poetry Analysis', 'thesis', 'Arts & Humanities', 'LIT-305', 'Nusrat Jahan', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', now() - interval '1 week', 89),
('Anatomy Lab Report Template', 'paper', 'Medical Sciences', 'MED-102', 'Jamal Uddin', 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf', now() - interval '2 weeks', 230);

-- Submissions (Pending)
INSERT INTO submissions (type, "studentName", department, content, status) VALUES
('biography', 'Mehedi Hasan', 'Computer Science', '{"bio": "Looking to join the dev community.", "email": "mehedi@example.com"}', 'pending'),
('resource', 'Rina Begum', 'Arts & Humanities', '{"title": "History Notes", "description": "Chapter 1-5 summary"}', 'pending'),
('biography', 'Tariq Islam', 'Engineering', '{"bio": "Electrical engineering student.", "email": "tariq@example.com"}', 'pending'),
('resource', 'Sohana Parvin', 'Business Administration', '{"title": "Case Study 4", "description": "Analysis of local market"}', 'pending'),
('biography', 'Kabir Hossain', 'Medical Sciences', '{"bio": "Future doctor.", "email": "kabir@example.com"}', 'pending');

-- Campus Images (Slideshow)
INSERT INTO campus_images (url) VALUES
('https://images.unsplash.com/photo-1523050854058-8df90110c9f1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
('https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80'),
('https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-1.2.1&auto=format&fit=crop&w=1350&q=80');
